name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    services:
      consul:
        image: consul:1.10.3
        env:
          CONSUL_BIND_INTERFACE: eth0
        ports:
          - 8300-8302:8300-8302/tcp
          - 8301-8302:8301-8302/udp
          - 8500:8500/tcp
          - 8600:8600/tcp
          - 8600:8600/udp
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: make test && make coverage
        env:
          DEREGISTER_CRITICAL_SERVICE_AFTER_SECONDS: 25
      - name: Show Service Error
        if: ${{ failure() }}
        run: |
          curl http://localhost:8500/v1/health/service/balancer-server?passing=1&tag=test
          docker logs "${{ job.services.consul.id }}"

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/coverage.out